/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun NombreApellido(){
    val nombre: String = "Facu"
    val edad: Int = 16


    println("Hola: $nombre")
    println("Tenes: $edad")
}

fun main() {
    println("¡Hola, Kotlin!")
    NombreApellido()
}