/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun NombreEdad(){
    val nombre: String = "Facu"
    val edad: Int = 16

    println("Hola: $nombre")
    println("Tenes: $edad")
}

fun mostrarTiposDeDatos() {
    val nombre: String = "Juan"
    val edad: Int = 25
    val altura: Double = 1.75
    val esEstudiante: Boolean = true
    
    println("Nombre: $nombre")
    println("Edad: $edad")
    println("Altura: $altura")
    println("Es estudiante: $esEstudiante")
}

fun triangulorec(){
    val base: Double = 5.8
    val altura: Double = 3.7

    val area = base*altura
    println("El area de triangulo es: $area m2")
}



fun esParOImpar(numero: Int = 5): String {
    return when {
        numero % 2 == 0 -> "Par"
        else -> "Impar"
    }
}

fun PositivoNegativo(){
    val numero2: Double = -5.0

    if (numero2 > 0){
        println("El numero es positivo")
    }

    if (numero2 < 0){
        println("El numero es negativo ")
    }
}

fun mostrarNumerosPares() {
    println("Usando for:")
    for (i in 1..10) {
        if (i % 2 == 0) { 
            println(i)
        }
    }
    
    println("Usando while:")
    var j = 1
    while (j <= 10) {
        if (j % 2 == 0) { 
            println(j)
        }
        j++
    }
    
    println("\nUsando do-while:")
    var k = 1
    do {
        if (k % 2 == 0) { 
            println(k)
        }
        k++
    } while (k <= 10)
}

fun factorial(n: Int): Int {
    return if (n <= 1) 1 else n * factorial(n - 1)
}

fun saludar(nombre: String, edad: Int = 0) {
    println("Hola $nombre, tienes $edad años")
}

fun elevarExponente() {
    val base2: Int = 2
    val exponente2: Int = 2

    val resultado = Math.pow(base2.toDouble(), exponente2.toDouble())
    println("La potencia es: $resultado")
}

fun main() {
    NombreEdad()
}